me = "routing_analysis"
authors = ["Thomas Dickson"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
IteratorInterfaceExtensions = "82899510-4779-5014-852e-03e436cf321d"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
sail_route = "115e5196-f809-57df-8580-7a2e8d592fff"
